FROM node:20-slim
WORKDIR /app

RUN rm -rf node_modules package-lock.json

COPY package.json ./


RUN npm install typescript@5 --save-dev --legacy-peer-deps


RUN npm install --legacy-peer-deps

COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]